version: "3"

services:
  v2ray:
    image: ghcr.io/v2fly/v2ray:v5.16.1
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "1310:1310"
    volumes:
      - ./v2ray/config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/
