version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:v5.15.1
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    volumes:
      - ./v2ray/config/:/etc/v2ray/
      - ./v2ray/logs:/var/log/v2ray/
    ports:
      - "127.0.0.1:1310:1310"
      - "127.0.0.1:1310:1310/udp"
    entrypoint: ["/usr/bin/v2ray", "run", "--config=/etc/v2ray/config.json"]
  caddy:
    image: caddy:2.7.6-alpine
    restart: always
    ports:
      - "80:80"
      - "80:80/udp"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/web/:/usr/share/caddy
      - ./caddy/data/:/data/caddy/
      - ./caddy/config/:/config/caddy
